"""exam_engine

Revision ID: 2b7d99255d96
Revises: afa76289eedf
Create Date: 2026-06-02 10:45:10.033682
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2b7d99255d96'
down_revision: Union[str, None] = 'afa76289eedf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('exam_type_id', sa.String(length=36), nullable=False),
    sa.Column('subject_id', sa.String(length=36), nullable=True),
    sa.Column('year_level', sa.SmallInteger(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'review', 'approved', 'published', 'archived', name='exam_template_status'), nullable=False),
    sa.Column('created_by_admin_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_admin_id'], ['admin_profiles.id'], ),
    sa.ForeignKeyConstraint(['exam_type_id'], ['exam_types.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_templates_exam_type_id'), 'exam_templates', ['exam_type_id'], unique=False)
    op.create_index(op.f('ix_exam_templates_status'), 'exam_templates', ['status'], unique=False)
    op.create_table('exam_instances',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('exam_template_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'published', 'archived', name='exam_instance_status'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exam_template_id'], ['exam_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_instances_exam_template_id'), 'exam_instances', ['exam_template_id'], unique=False)
    op.create_index(op.f('ix_exam_instances_status'), 'exam_instances', ['status'], unique=False)
    op.create_table('exam_sections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('exam_template_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('order_index', sa.SmallInteger(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exam_template_id'], ['exam_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_sections_exam_template_id'), 'exam_sections', ['exam_template_id'], unique=False)
    op.create_table('attempts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('exam_instance_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('in_progress', 'submitted', 'expired', name='attempt_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('score_raw', sa.Integer(), nullable=True),
    sa.Column('score_percent', sa.Float(), nullable=True),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exam_instance_id'], ['exam_instances.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attempts_exam_instance_id'), 'attempts', ['exam_instance_id'], unique=False)
    op.create_index(op.f('ix_attempts_student_id'), 'attempts', ['student_id'], unique=False)
    op.create_table('exam_instance_questions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('exam_instance_id', sa.String(length=36), nullable=False),
    sa.Column('exam_section_id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('question_version_id', sa.String(length=36), nullable=False),
    sa.Column('order_index', sa.SmallInteger(), nullable=False),
    sa.Column('marks', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exam_instance_id'], ['exam_instances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exam_section_id'], ['exam_sections.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['question_version_id'], ['question_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_instance_questions_exam_instance_id'), 'exam_instance_questions', ['exam_instance_id'], unique=False)
    op.create_table('exam_section_questions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('exam_section_id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('order_index', sa.SmallInteger(), nullable=False),
    sa.Column('marks', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exam_section_id'], ['exam_sections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_section_questions_exam_section_id'), 'exam_section_questions', ['exam_section_id'], unique=False)
    op.create_table('attempt_answers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('attempt_id', sa.String(length=36), nullable=False),
    sa.Column('exam_instance_question_id', sa.String(length=36), nullable=False),
    sa.Column('selected_option', sa.String(length=10), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exam_instance_question_id'], ['exam_instance_questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attempt_answers_attempt_id'), 'attempt_answers', ['attempt_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attempt_answers_attempt_id'), table_name='attempt_answers')
    op.drop_table('attempt_answers')
    op.drop_index(op.f('ix_exam_section_questions_exam_section_id'), table_name='exam_section_questions')
    op.drop_table('exam_section_questions')
    op.drop_index(op.f('ix_exam_instance_questions_exam_instance_id'), table_name='exam_instance_questions')
    op.drop_table('exam_instance_questions')
    op.drop_index(op.f('ix_attempts_student_id'), table_name='attempts')
    op.drop_index(op.f('ix_attempts_exam_instance_id'), table_name='attempts')
    op.drop_table('attempts')
    op.drop_index(op.f('ix_exam_sections_exam_template_id'), table_name='exam_sections')
    op.drop_table('exam_sections')
    op.drop_index(op.f('ix_exam_instances_status'), table_name='exam_instances')
    op.drop_index(op.f('ix_exam_instances_exam_template_id'), table_name='exam_instances')
    op.drop_table('exam_instances')
    op.drop_index(op.f('ix_exam_templates_status'), table_name='exam_templates')
    op.drop_index(op.f('ix_exam_templates_exam_type_id'), table_name='exam_templates')
    op.drop_table('exam_templates')
    # ### end Alembic commands ###
