"""ocr_pipeline

Revision ID: 344f02b7d0c4
Revises: 63b2749eb252
Create Date: 2026-06-04 11:33:51.820143
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '344f02b7d0c4'
down_revision: Union[str, None] = '63b2749eb252'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ocr_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_format', sa.String(length=10), nullable=False),
    sa.Column('uploaded_by', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', name='ocr_job_status'), nullable=False),
    sa.Column('questions_detected', sa.Integer(), nullable=False),
    sa.Column('questions_created', sa.Integer(), nullable=False),
    sa.Column('ocr_results_json', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['admin_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ocr_page_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ocr_job_id', sa.String(length=36), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('structured_questions_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ocr_job_id'], ['ocr_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ocr_page_results_ocr_job_id'), 'ocr_page_results', ['ocr_job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ocr_page_results_ocr_job_id'), table_name='ocr_page_results')
    op.drop_table('ocr_page_results')
    op.drop_table('ocr_jobs')
    # ### end Alembic commands ###
