"""ai_generation_jobs

Revision ID: 47033109ef89
Revises: 344f02b7d0c4
Create Date: 2026-06-04 12:54:13.747193
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '47033109ef89'
down_revision: Union[str, None] = '344f02b7d0c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_generation_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('framework_id', sa.String(length=36), nullable=True),
    sa.Column('outcome_id', sa.String(length=36), nullable=True),
    sa.Column('subject_id', sa.String(length=36), nullable=False),
    sa.Column('exam_type_id', sa.String(length=36), nullable=False),
    sa.Column('difficulty_mix_json', sa.JSON(), nullable=True),
    sa.Column('requested_count', sa.Integer(), nullable=False),
    sa.Column('generated_count', sa.Integer(), nullable=False),
    sa.Column('saved_count', sa.Integer(), nullable=False),
    sa.Column('rejected_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'completed', 'failed', name='ai_generation_job_status'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_by_admin_id', sa.String(length=36), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_admin_id'], ['admin_profiles.id'], ),
    sa.ForeignKeyConstraint(['exam_type_id'], ['exam_types.id'], ),
    sa.ForeignKeyConstraint(['framework_id'], ['curriculum_frameworks.id'], ),
    sa.ForeignKeyConstraint(['outcome_id'], ['curriculum_outcomes.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_generation_jobs')
    # ### end Alembic commands ###
