"""content_review_workflow

Revision ID: 49edca405048
Revises: b33ad14c121a
Create Date: 2026-06-03 06:27:45.820456
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '49edca405048'
down_revision: Union[str, None] = 'b33ad14c121a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('quality_score', sa.SmallInteger(), nullable=True))
    op.add_column('questions', sa.Column('review_notes', sa.Text(), nullable=True))
    op.add_column('questions', sa.Column('reviewed_by_admin_id', sa.String(length=36), nullable=True))
    op.add_column('questions', sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('questions', sa.Column('published_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'questions', 'admin_profiles', ['reviewed_by_admin_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_column('questions', 'published_at')
    op.drop_column('questions', 'reviewed_at')
    op.drop_column('questions', 'reviewed_by_admin_id')
    op.drop_column('questions', 'review_notes')
    op.drop_column('questions', 'quality_score')
    # ### end Alembic commands ###
