"""ai_token_usage

Revision ID: 4a60f9fbe0c7
Revises: 47033109ef89
Create Date: 2026-06-05 07:13:42.088194
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4a60f9fbe0c7'
down_revision: Union[str, None] = '47033109ef89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_generation_jobs', sa.Column('token_usage_json', sa.JSON(), nullable=True))
    op.add_column('ai_generation_jobs', sa.Column('estimated_cost', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_generation_jobs', 'estimated_cost')
    op.drop_column('ai_generation_jobs', 'token_usage_json')
    # ### end Alembic commands ###
