"""integrity_and_time_tracking

Revision ID: 975a71b88521
Revises: d733c23af59c
Create Date: 2026-06-02 12:31:25.647092
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '975a71b88521'
down_revision: Union[str, None] = 'd733c23af59c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attempt_integrity_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('attempt_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attempt_integrity_events_attempt_id'), 'attempt_integrity_events', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_attempt_integrity_events_event_type'), 'attempt_integrity_events', ['event_type'], unique=False)
    op.add_column('attempt_answers', sa.Column('time_spent_seconds', sa.Integer(), nullable=False))
    op.add_column('attempts', sa.Column('integrity_summary_json', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attempts', 'integrity_summary_json')
    op.drop_column('attempt_answers', 'time_spent_seconds')
    op.drop_index(op.f('ix_attempt_integrity_events_event_type'), table_name='attempt_integrity_events')
    op.drop_index(op.f('ix_attempt_integrity_events_attempt_id'), table_name='attempt_integrity_events')
    op.drop_table('attempt_integrity_events')
    # ### end Alembic commands ###
