"""parent_assignment

Revision ID: aaaf997b27d6
Revises: 975a71b88521
Create Date: 2026-06-02 13:19:34.499448
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'aaaf997b27d6'
down_revision: Union[str, None] = '975a71b88521'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assigned_exams',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('exam_instance_id', sa.String(length=36), nullable=False),
    sa.Column('assigned_by_parent_id', sa.String(length=36), nullable=False),
    sa.Column('title_snapshot', sa.String(length=255), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('assigned', 'started', 'completed', 'overdue', 'cancelled', name='assignment_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_parent_id'], ['parent_profiles.id'], ),
    sa.ForeignKeyConstraint(['exam_instance_id'], ['exam_instances.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assigned_exams_exam_instance_id'), 'assigned_exams', ['exam_instance_id'], unique=False)
    op.create_index(op.f('ix_assigned_exams_status'), 'assigned_exams', ['status'], unique=False)
    op.create_index(op.f('ix_assigned_exams_student_id'), 'assigned_exams', ['student_id'], unique=False)
    op.add_column('attempts', sa.Column('assigned_exam_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_attempts_assigned_exam_id'), 'attempts', ['assigned_exam_id'], unique=False)
    op.create_foreign_key(None, 'attempts', 'assigned_exams', ['assigned_exam_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'attempts', type_='foreignkey')
    op.drop_index(op.f('ix_attempts_assigned_exam_id'), table_name='attempts')
    op.drop_column('attempts', 'assigned_exam_id')
    op.drop_index(op.f('ix_assigned_exams_student_id'), table_name='assigned_exams')
    op.drop_index(op.f('ix_assigned_exams_status'), table_name='assigned_exams')
    op.drop_index(op.f('ix_assigned_exams_exam_instance_id'), table_name='assigned_exams')
    op.drop_table('assigned_exams')
    # ### end Alembic commands ###
