"""question_bank_foundation

Revision ID: afa76289eedf
Revises: b6a41ed04bcd
Create Date: 2026-06-02 07:56:50.702059
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'afa76289eedf'
down_revision: Union[str, None] = 'b6a41ed04bcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_types',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_types_code'), 'exam_types', ['code'], unique=True)
    op.create_table('subjects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subjects_code'), 'subjects', ['code'], unique=True)
    op.create_table('skill_tags',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('subject_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('subject_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topics_subject_id'), 'topics', ['subject_id'], unique=False)
    op.create_table('question_pools',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('subject_id', sa.String(length=36), nullable=True),
    sa.Column('exam_type_id', sa.String(length=36), nullable=True),
    sa.Column('year_level', sa.SmallInteger(), nullable=True),
    sa.Column('pool_type', sa.Enum('static', 'dynamic', name='pool_type'), nullable=False),
    sa.Column('query_criteria_json', sa.JSON(), nullable=True),
    sa.Column('created_by_admin_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_admin_id'], ['admin_profiles.id'], ),
    sa.ForeignKeyConstraint(['exam_type_id'], ['exam_types.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('subject_id', sa.String(length=36), nullable=False),
    sa.Column('exam_type_id', sa.String(length=36), nullable=False),
    sa.Column('year_level', sa.SmallInteger(), nullable=False),
    sa.Column('topic_id', sa.String(length=36), nullable=True),
    sa.Column('difficulty', sa.Enum('easy', 'medium', 'hard', name='difficulty_level'), nullable=False),
    sa.Column('question_type', sa.Enum('mcq', 'short_answer', 'extended_response', name='question_type_enum'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'review', 'approved', 'published', 'archived', 'rejected', name='question_status'), nullable=False),
    sa.Column('source_type', sa.Enum('manual', 'ocr', 'ai', name='source_type'), nullable=False),
    sa.Column('content_ownership', sa.Enum('original', 'licensed', 'public_domain', 'approved_internal', 'user_provided_with_rights', 'internal_draft', 'restricted_reference_only', name='content_ownership_type'), nullable=False),
    sa.Column('copyright_note', sa.Text(), nullable=True),
    sa.Column('current_version_id', sa.String(length=36), nullable=True),
    sa.Column('created_by_admin_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_admin_id'], ['admin_profiles.id'], ),
    sa.ForeignKeyConstraint(['current_version_id'], ['question_versions.id'], name='fk_question_current_version_id', use_alter=True),
    sa.ForeignKeyConstraint(['exam_type_id'], ['exam_types.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_exam_type_id'), 'questions', ['exam_type_id'], unique=False)
    op.create_index(op.f('ix_questions_status'), 'questions', ['status'], unique=False)
    op.create_index(op.f('ix_questions_subject_id'), 'questions', ['subject_id'], unique=False)
    op.create_table('question_pool_memberships',
    sa.Column('pool_id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('added_by_admin_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['added_by_admin_id'], ['admin_profiles.id'], ),
    sa.ForeignKeyConstraint(['pool_id'], ['question_pools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('pool_id', 'question_id')
    )
    op.create_table('question_skill_tags',
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('skill_tag_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_tag_id'], ['skill_tags.id'], ),
    sa.PrimaryKeyConstraint('question_id', 'skill_tag_id')
    )
    op.create_table('question_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('stem', sa.Text(), nullable=False),
    sa.Column('correct_answer', sa.String(length=255), nullable=True),
    sa.Column('full_explanation', sa.Text(), nullable=False),
    sa.Column('marks', sa.SmallInteger(), nullable=False),
    sa.Column('options_json', sa.JSON(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_by_admin_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_admin_id'], ['admin_profiles.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_versions_question_id'), 'question_versions', ['question_id'], unique=False)
    op.create_table('question_media',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('question_version_id', sa.String(length=36), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('media_type', sa.Enum('image', 'audio', name='media_type'), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['question_version_id'], ['question_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_media_question_version_id'), 'question_media', ['question_version_id'], unique=False)
    # Deferred FK: questions.current_version_id → question_versions.id
    # (use_alter=True in model; must be added after question_versions table exists)
    op.create_foreign_key(
        "fk_question_current_version_id",
        "questions",
        "question_versions",
        ["current_version_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_question_current_version_id", "questions", type_="foreignkey")
    op.drop_index(op.f('ix_question_media_question_version_id'), table_name='question_media')
    op.drop_table('question_media')
    op.drop_index(op.f('ix_question_versions_question_id'), table_name='question_versions')
    op.drop_table('question_versions')
    op.drop_table('question_skill_tags')
    op.drop_table('question_pool_memberships')
    op.drop_index(op.f('ix_questions_subject_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_status'), table_name='questions')
    op.drop_index(op.f('ix_questions_exam_type_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_table('question_pools')
    op.drop_index(op.f('ix_topics_subject_id'), table_name='topics')
    op.drop_table('topics')
    op.drop_table('skill_tags')
    op.drop_index(op.f('ix_subjects_code'), table_name='subjects')
    op.drop_table('subjects')
    op.drop_index(op.f('ix_exam_types_code'), table_name='exam_types')
    op.drop_table('exam_types')
    # ### end Alembic commands ###
