"""curriculum_mapping

Revision ID: b33ad14c121a
Revises: aaaf997b27d6
Create Date: 2026-06-03 00:25:37.769076
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b33ad14c121a'
down_revision: Union[str, None] = 'aaaf997b27d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curriculum_frameworks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('exam_type_id', sa.String(length=36), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exam_type_id'], ['exam_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_curriculum_frameworks_exam_type_id'), 'curriculum_frameworks', ['exam_type_id'], unique=False)
    op.create_table('curriculum_outcomes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('framework_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['framework_id'], ['curriculum_frameworks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_curriculum_outcomes_framework_id'), 'curriculum_outcomes', ['framework_id'], unique=False)
    op.create_table('question_outcome_mappings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('outcome_id', sa.String(length=36), nullable=False),
    sa.Column('weight', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['outcome_id'], ['curriculum_outcomes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'outcome_id', name='uq_question_outcome')
    )
    op.create_index(op.f('ix_question_outcome_mappings_outcome_id'), 'question_outcome_mappings', ['outcome_id'], unique=False)
    op.create_index(op.f('ix_question_outcome_mappings_question_id'), 'question_outcome_mappings', ['question_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_question_outcome_mappings_question_id'), table_name='question_outcome_mappings')
    op.drop_index(op.f('ix_question_outcome_mappings_outcome_id'), table_name='question_outcome_mappings')
    op.drop_table('question_outcome_mappings')
    op.drop_index(op.f('ix_curriculum_outcomes_framework_id'), table_name='curriculum_outcomes')
    op.drop_table('curriculum_outcomes')
    op.drop_index(op.f('ix_curriculum_frameworks_exam_type_id'), table_name='curriculum_frameworks')
    op.drop_table('curriculum_frameworks')
    # ### end Alembic commands ###
