"""analytics

Revision ID: d733c23af59c
Revises: 2b7d99255d96
Create Date: 2026-06-02 11:50:38.314828
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd733c23af59c'
down_revision: Union[str, None] = '2b7d99255d96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skill_performance',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('skill_tag_id', sa.String(length=36), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('accuracy_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('average_time_seconds', sa.Numeric(precision=6, scale=1), nullable=False),
    sa.Column('last_calculated_at', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['skill_tag_id'], ['skill_tags.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_performance_skill_tag_id'), 'skill_performance', ['skill_tag_id'], unique=False)
    op.create_index(op.f('ix_skill_performance_student_id'), 'skill_performance', ['student_id'], unique=False)
    op.create_table('topic_performance',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('topic_id', sa.String(length=36), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('accuracy_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('average_time_seconds', sa.Numeric(precision=6, scale=1), nullable=False),
    sa.Column('last_calculated_at', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topic_performance_student_id'), 'topic_performance', ['student_id'], unique=False)
    op.create_index(op.f('ix_topic_performance_topic_id'), 'topic_performance', ['topic_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_topic_performance_topic_id'), table_name='topic_performance')
    op.drop_index(op.f('ix_topic_performance_student_id'), table_name='topic_performance')
    op.drop_table('topic_performance')
    op.drop_index(op.f('ix_skill_performance_student_id'), table_name='skill_performance')
    op.drop_index(op.f('ix_skill_performance_skill_tag_id'), table_name='skill_performance')
    op.drop_table('skill_performance')
    # ### end Alembic commands ###
